export interface ApplyOption {
  publisher: string;
  applyLink: string;
}

/** Normalized job from generated jobs JSON feed. */
export interface Job {
  id: string;
  title: string;
  company: string;
  location: string;
  postedAt: string | null;
  postedDisplay: string | null;
  description: string;
  salaryDisplay: string | null;
  listingSource: string | null;
  jobPublisher?: string | null;
  jobMinSalary?: number | null;
  jobMaxSalary?: number | null;
  jobMedianSalary?: number | null;
  jobSalaryCurrency?: string | null;
  jobSalaryPeriod?: string | null;
  jobCity?: string | null;
  jobState?: string | null;
  jobCountry?: string | null;
  jobLocation?: string | null;
  employerName?: string | null;
  applyOptions?: ApplyOption[];
  /** AI summary generated by backend feed builder. */
  aiSummary?: string | null;
  /** AI Toronto office location generated by backend feed builder. */
  aiOfficeLocationToronto?: string | null;
  /** Optional snake_case variant from raw generated JSON payloads. */
  office_location_toronto?: string | null;
  aiSummaryError?: string | null;
}

export interface JobsSearchResponse {
  jobs: Job[];
}
